version: '3'
services:
  mariadb:
    image: mariadb:10.4.27
    container_name: my-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: 6yVXoz+RLF2NXmwHnp/ffnzFZ
      MYSQL_DATABASE: streaming
      MYSQL_USER: streaming_user
      MYSQL_PASSWORD: YAM7iqKzodHNJTHRuNsSjHhCDcrWAdrxhOO79B
    ports:
      - "3306:3306"
    volumes:
      - ./streaming.sql:/docker-entrypoint-initdb.d/init.sql

  flaskapp:
    build: ./python
    environment:
      SERVER_IP: 116.204.180.51
      MYSQL_HOST: 116.204.180.51
      MYSQL_USER: streaming_user
      MYSQL_DATABASE: streaming
      MYSQL_PASSWORD: YAM7iqKzodHNJTHRuNsSjHhCDcrWAdrxhOO79B
    ports:
      - "8900:8900"
    volumes:
      - ./python:/app

  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
