# Use an official Python runtime as a parent image
FROM python

# Set the working directory in the container
WORKDIR /app

# Install system dependencies including libgl1-mesa-glx
RUN apt-get update && apt-get install -y ffmpeg libgl1-mesa-glx

# Copy the requirements file into the container at /app
COPY ./requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Copy the current directory contents into the container at /app
COPY . /app

# Run app.py when the container launches
CMD ["python", "./main_flask.py"]
